render: false
opponent_controller_type: "DecisionBasedController"
reward:
  step: 0
  target_hit:
    start: 1
    end: 0.05
    decay: 40000
  shot_fired: 0
  taken_damage:
    start: -1
    end: -0.05
    decay: 40000
  game_lost:
    start: -1
    end: -10
    decay: 40000
  game_won:
    start: 1
    end: 10
    decay: 40000
  action_taken: 0
  shot_fired_when_on_cooldown: 0
max_steps: .inf
step_delay: 5
use_simplified_environment_actions: false