player_1:
  x_constraint: [0, 400] # from 0 to width
  y_constraint: [25, 175]
  color: [255, 0, 0]
  bullet_color: [255, 0, 0]
  base_size: 32
  velocity: 14
  max_hitpoints: 5
  acceleration: 1
player_2:
  x_constraint: [0, 400] # from 0 to width
  y_constraint: [225, 375]
  color: [0, 0, 255]
  bullet_color: [0, 0, 255]
  base_size: 32
  velocity: 14
  max_hitpoints: 5
  acceleration: 1
ai_input_lag: 5
scale: 1
base_width: 400
base_height: 400
compressed_width: 64
compressed_height: 64
bullet:
  base_width: 16
  base_height: 16
  velocity: 16
ammo:
  cooldown: 10
  maximum: 20
  countdown: 80
fps: 20
information_display_box_size: 8

